######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 4 15:17:14 2017
######################################################################

TEMPLATE = app
TARGET = contace
DEPENDPATH += .
INCLUDEPATH += .


QT += gui sql

# Input
HEADERS += contact.h
SOURCES += main.cpp \
    contact.cpp
